# Generated by Django 3.1 on 2020-10-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200920_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/'),
        ),
    ]
